"""Initial migration

Revision ID: 055017636bc9
Revises: 
Create Date: 2024-06-12 22:43:48.548797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '055017636bc9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carrier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('company', sa.String(length=64), nullable=False),
    sa.Column('address', sa.String(length=128), nullable=False),
    sa.Column('allowed_items', sa.JSON(), nullable=True),
    sa.Column('max_load_quantity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('produce_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carrier_produce_item',
    sa.Column('carrier_id', sa.Integer(), nullable=False),
    sa.Column('produce_item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['carrier_id'], ['carrier.id'], ),
    sa.ForeignKeyConstraint(['produce_item_id'], ['produce_item.id'], ),
    sa.PrimaryKeyConstraint('carrier_id', 'produce_item_id')
    )
    op.create_table('crop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produce_item_id', sa.Integer(), nullable=False),
    sa.Column('carrier_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('harvest_date', sa.Date(), nullable=False),
    sa.Column('farmer', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['carrier_id'], ['carrier.id'], ),
    sa.ForeignKeyConstraint(['produce_item_id'], ['produce_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('load',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer', sa.String(length=64), nullable=False),
    sa.Column('carrier_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['carrier_id'], ['carrier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('load_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produce_item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('load_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['load_id'], ['load.id'], ),
    sa.ForeignKeyConstraint(['produce_item_id'], ['produce_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('load_produce_item',
    sa.Column('load_id', sa.Integer(), nullable=False),
    sa.Column('produce_item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['load_id'], ['load.id'], ),
    sa.ForeignKeyConstraint(['produce_item_id'], ['produce_item.id'], ),
    sa.PrimaryKeyConstraint('load_id', 'produce_item_id'),
    info={'bind_key': None}
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('load_produce_item')
    op.drop_table('load_item')
    op.drop_table('load')
    op.drop_table('crop')
    op.drop_table('carrier_produce_item')
    op.drop_table('produce_item')
    op.drop_table('carrier')
    # ### end Alembic commands ###
