version: '3.7'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DATABASE_URL=sqlite:///app.db
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"